M48
; DRILL file {KiCad 8.0.8} date 2025-04-01T17:59:16+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-01T17:59:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.33Y-3.6008
X4.33Y-3.8008
T2
X4.2913Y-4.1732
X4.3913Y-4.1732
M30
